### ISSUE TITLE
Minify the mvc-grid.js having some compilation errors.

### ISSUE THREAD

**Issue by digvijaypundir1** [NonFactors/AspNetCore.Grid#296]
I have been using BuildBundleMinifier (https://www.nuget.org/packages/buildbundlerminifier/) for minify the javascript files in my asp.net core project. I am using your NonFactors.Grid.Core.Mvc6  for grid. Initially we were using v5.1.1 where there is no problem while minifying the mvc-grid.js but when we update our grid version to v6.2.0 (latest) one we are facing some compilation issues.

There are 2 errors in mvc-grid.js file and i have made these changes to run the file:

1. **Compilation error:** Change `set(option) {`  method (Line no 68) to `setGrid(option) {` because `set` method name is having problem with compilation.
2. **Filter is not working due to variable javascript error:** Change in `apply() {` method (Line no 446) : Change in `for (const column of grid.columns) {` I have replaced it with `for (const column of this.column.grid.columns) {` So used direct grid reference instead of variable.

May be you can check them by your self and make the changes. And if i am making any mistake let me know. As i have also used the latest bundle minifier update with no luck.
